// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFa978fVNLr_WIOkfQg6QbPlGPY5kjgz4',
    appId: '1:229713434653:web:876c4e2887f916d9350ef4',
    messagingSenderId: '229713434653',
    projectId: 'spacecabapp',
    authDomain: 'spacecabapp.firebaseapp.com',
    storageBucket: 'spacecabapp.firebasestorage.app',
    measurementId: 'G-JS3NDR5LH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDRwsBHDnZEUsACGk5bl8C3fmv0VuLzQU',
    appId: '1:229713434653:android:90c0f39951d0d7c0350ef4',
    messagingSenderId: '229713434653',
    projectId: 'spacecabapp',
    storageBucket: 'spacecabapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVfCZjRtZzz2cPTjqXa5V9XlX6Ngap9Ag',
    appId: '1:229713434653:ios:792a455c0ee23aa6350ef4',
    messagingSenderId: '229713434653',
    projectId: 'spacecabapp',
    storageBucket: 'spacecabapp.firebasestorage.app',
    iosBundleId: 'com.example.spacecab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVfCZjRtZzz2cPTjqXa5V9XlX6Ngap9Ag',
    appId: '1:229713434653:ios:792a455c0ee23aa6350ef4',
    messagingSenderId: '229713434653',
    projectId: 'spacecabapp',
    storageBucket: 'spacecabapp.firebasestorage.app',
    iosBundleId: 'com.example.spacecab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFa978fVNLr_WIOkfQg6QbPlGPY5kjgz4',
    appId: '1:229713434653:web:408c88523aeeb117350ef4',
    messagingSenderId: '229713434653',
    projectId: 'spacecabapp',
    authDomain: 'spacecabapp.firebaseapp.com',
    storageBucket: 'spacecabapp.firebasestorage.app',
    measurementId: 'G-F1CWLT2FXL',
  );
}
